import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../shared/utils/ui_helpers.dart';
import '../models/farm_model.dart';
import '../providers/farm_provider.dart';

class AddEditFarmScreen extends ConsumerStatefulWidget {
  const AddEditFarmScreen({super.key, this.farm});

  final FarmModel? farm;

  @override
  ConsumerState<AddEditFarmScreen> createState() => _AddEditFarmScreenState();
}

class _AddEditFarmScreenState extends ConsumerState<AddEditFarmScreen> {
  final _formKey = GlobalKey<FormState>();

  late final TextEditingController _nameCtrl;
  late final TextEditingController _ownerCtrl;
  late final TextEditingController _phoneCtrl;
  late final TextEditingController _addressCtrl;
  late final TextEditingController _shedsCtrl;
  late final TextEditingController _capacityCtrl;
  late final TextEditingController _notesCtrl;

  String _selectedType = 'Broiler';
  final List<String> _farmTypes = ['Broiler', 'Layer', 'Country Chicken'];

  @override
  void initState() {
    super.initState();
    _nameCtrl = TextEditingController(text: widget.farm?.name);
    _ownerCtrl = TextEditingController(text: widget.farm?.ownerName);
    _phoneCtrl = TextEditingController(text: widget.farm?.phone);
    _addressCtrl = TextEditingController(text: widget.farm?.address);
    _shedsCtrl = TextEditingController(text: widget.farm?.sheds.toString());
    _capacityCtrl = TextEditingController(
      text: widget.farm?.capacity.toString(),
    );
    _notesCtrl = TextEditingController(text: widget.farm?.notes);

    if (widget.farm != null && _farmTypes.contains(widget.farm!.type)) {
      _selectedType = widget.farm!.type;
    }
  }

  @override
  void dispose() {
    _nameCtrl.dispose();
    _ownerCtrl.dispose();
    _phoneCtrl.dispose();
    _addressCtrl.dispose();
    _shedsCtrl.dispose();
    _capacityCtrl.dispose();
    _notesCtrl.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    final isEditing = widget.farm != null;

    final farmData = FarmModel(
      id:
          widget.farm?.id ??
          '', // ID generated by Firestore if empty (Wait, addFarm doesn't use the model ID)
      name: _nameCtrl.text.trim(),
      type: _selectedType,
      ownerName: _ownerCtrl.text.trim(),
      phone: _phoneCtrl.text.trim(),
      address: _addressCtrl.text.trim(),
      sheds: int.tryParse(_shedsCtrl.text.trim()) ?? 0,
      capacity: int.tryParse(_capacityCtrl.text.trim()) ?? 0,
      notes: _notesCtrl.text.trim(),
      ownerId: widget.farm?.ownerId ?? '', // Handled by repository
      createdAt: widget.farm?.createdAt,
    );

    // 1. Show Loading Dialog
    UiHelpers.showLoadingDialog(
      context,
      isEditing ? 'Updating Farm...' : 'Saving Farm...',
      isEditing ? 'Please wait...' : 'Please wait while we save your farm.',
    );

    // 2. Perform action
    if (isEditing) {
      await ref.read(farmControllerProvider.notifier).updateFarm(farmData);
    } else {
      await ref.read(farmControllerProvider.notifier).addFarm(farmData);
    }

    if (!mounted) return;

    // 3. Close Loading Dialog
    context.pop();

    // 4. Handle Result
    final error = ref.read(farmControllerProvider).error;
    if (error != null) {
      UiHelpers.showErrorDialog(context, error.toString());
    } else {
      await UiHelpers.showSuccessDialog(
        context,
        isEditing ? 'Farm Updated Successfully' : 'Farm Saved Successfully',
        isEditing ? '' : 'Your farm has been added successfully.',
        duration: const Duration(milliseconds: 400),
      );
      if (mounted) context.pop(); // Return to previous screen
    }
  }

  @override
  Widget build(BuildContext context) {
    final isEditing = widget.farm != null;
    final state = ref.watch(farmControllerProvider);

    return Scaffold(
      appBar: AppBar(title: Text(isEditing ? 'Edit Farm' : 'Add Farm')),
      body: SafeArea(
        child: IgnorePointer(
          ignoring: state.isLoading,
          child: Form(
            key: _formKey,
            child: ListView(
              padding: const EdgeInsets.all(24.0),
              children: [
                TextFormField(
                  controller: _nameCtrl,
                  decoration: const InputDecoration(
                    labelText: 'Farm Name',
                    prefixIcon: Icon(Icons.business),
                  ),
                  validator: (val) =>
                      val == null || val.isEmpty ? 'Required' : null,
                ),
                const SizedBox(height: 16),

                DropdownButtonFormField<String>(
                  initialValue: _selectedType,
                  decoration: const InputDecoration(
                    labelText: 'Farm Type',
                    prefixIcon: Icon(Icons.category),
                  ),
                  items: _farmTypes.map((type) {
                    return DropdownMenuItem(value: type, child: Text(type));
                  }).toList(),
                  onChanged: (val) {
                    if (val != null) setState(() => _selectedType = val);
                  },
                ),
                const SizedBox(height: 16),

                TextFormField(
                  controller: _ownerCtrl,
                  decoration: const InputDecoration(
                    labelText: 'Owner Name',
                    prefixIcon: Icon(Icons.person),
                  ),
                  validator: (val) =>
                      val == null || val.isEmpty ? 'Required' : null,
                ),
                const SizedBox(height: 16),

                TextFormField(
                  controller: _phoneCtrl,
                  decoration: const InputDecoration(
                    labelText: 'Phone Number',
                    prefixIcon: Icon(Icons.phone),
                  ),
                  keyboardType: TextInputType.phone,
                ),
                const SizedBox(height: 16),

                TextFormField(
                  controller: _addressCtrl,
                  decoration: const InputDecoration(
                    labelText: 'Address',
                    prefixIcon: Icon(Icons.location_on),
                  ),
                  maxLines: 2,
                ),
                const SizedBox(height: 16),

                Row(
                  children: [
                    Expanded(
                      child: TextFormField(
                        controller: _shedsCtrl,
                        decoration: const InputDecoration(
                          labelText: 'Number of Sheds',
                          prefixIcon: Icon(Icons.house_siding),
                        ),
                        keyboardType: TextInputType.number,
                        validator: (val) =>
                            val == null || val.isEmpty ? 'Required' : null,
                      ),
                    ),
                    const SizedBox(width: 16),
                    Expanded(
                      child: TextFormField(
                        controller: _capacityCtrl,
                        decoration: const InputDecoration(
                          labelText: 'Total Capacity',
                          prefixIcon: Icon(Icons.group),
                        ),
                        keyboardType: TextInputType.number,
                        validator: (val) =>
                            val == null || val.isEmpty ? 'Required' : null,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 16),

                TextFormField(
                  controller: _notesCtrl,
                  decoration: const InputDecoration(
                    labelText: 'Notes',
                    prefixIcon: Icon(Icons.notes),
                  ),
                  maxLines: 3,
                ),
                const SizedBox(height: 32),

                FilledButton(
                  onPressed: state.isLoading ? null : _submit,
                  style: FilledButton.styleFrom(
                    padding: const EdgeInsets.symmetric(vertical: 16),
                  ),
                  child: FittedBox(
                    fit: BoxFit.scaleDown,
                    child: Text(isEditing ? 'Update Farm' : 'Save Farm'),
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
